version: '3'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - BASE_PATH=/app
      - WITH_PROMETHEUS=false

  prometheus:
    image: prom/prometheus
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
  grafana:
    image: 'grafana/grafana:8.2.5'
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
volumes:
  grafana_storage: null
