{
 "title": "Compress and Decompress",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Compression Count ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "compression_count_total{operation=\"compress\"}"
    }
   ]
  },
  {
   "title": "Average Compress Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(compression_duration_seconds_sum{operation=\"compress\"}) / sum(compression_duration_seconds_count{operation=\"compress\"})"
    }
   ]
  },
  {
   "title": "Decompress Count ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "compression_count_total{operation=\"decompress\"}"
    }
   ]
  },
  {
   "title": "Average Decompress Time",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(compression_duration_seconds_sum{operation=\"decompress\"}) / sum(compression_duration_seconds_count{operation=\"decompress\"})"
    }
   ]
  }
 ]
}